# Assignment No. 1

# Implementation of 50 methods of numpy.

In [1]:
import numpy as np

# 1. arange function

In [2]:
# it return evenly spaced values within a given interval.

In [3]:
a = np.arange(16)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
a = np.arange(10,40,5)

In [6]:
a

array([10, 15, 20, 25, 30, 35])

# 2. array function 

In [7]:
# it create an array.

In [8]:
b = np.array([(1,2,3),(4,5,6)])    # two dimensional array

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

# 3. zeros function

In [10]:
#it returns a new array of given shape and type, filled with zeros.

In [11]:
c = np.zeros((4,5))

In [12]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 4. ones function

In [13]:
#it returns a new array of given shape and type, filled with ones.

In [14]:
d = np.ones((3,2,4))

In [15]:
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# 5. empty function

In [16]:
#it returns a new array of given shape and type, without initializing entries.

In [17]:
e = np.empty((2,3))

In [18]:
e

array([[0., 0., 0.],
       [0., 0., 0.]])

# 6. linspace function

In [19]:
# it returns evenly spaced numbers over a specified interval.

In [20]:
f = np.linspace(0,1,5)

In [21]:
f

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 7. reshape function

In [22]:
#it gives a new shape to an array without changing its data.

In [23]:
g = np.arange(20).reshape(4,5)   # two dimensional array

In [24]:
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
g = np.arange(24).reshape(2,3,4)  # three dimensional array

In [26]:
g

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# 8. sum function

In [27]:
# Sum of array elements over a given axis.

In [28]:
h = np.arange(20).reshape(4,5)

In [29]:
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
h.sum(axis=0)    #sum of each column

array([30, 34, 38, 42, 46])

# 9. cumsum function

In [31]:
# it return the cumulative sum of the elements along a given axis.

In [32]:
i = np.arange(20).reshape(4,5)

In [33]:
i.cumsum(axis=1)    # cumulative sum along each row

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60],
       [15, 31, 48, 66, 85]], dtype=int32)

# 10. min function

In [34]:
# it return the smallest item in an iterable or the smallest of two or more arguments.

In [35]:
j = np.arange(20).reshape(4,5)

In [36]:
j.min(axis=1)    # minimum value of each raw

array([ 0,  5, 10, 15])

# 11. zeros_like function

In [37]:
# it return an array of zeros with the same shape and type as a given array.

In [38]:
k = np.arange(9).reshape(3,3)

In [39]:
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
np.zeros_like(k)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# 12. ones_like function

In [41]:
# it return an array of ones with the same shape and type as a given array.

In [42]:
l = np.arange(12).reshape(3,4)

In [43]:
l

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.ones_like(l)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 13. empty_like function

In [45]:
# it return a new array with the same shape and type as a given array.

In [46]:
m = ([1,2,3],[4,5,6])

In [47]:
np.empty_like(m)

array([[-1300598272,         448,           0],
       [          0,      131074,     4391004]])

# 14. all function

In [48]:
# it test whether all array elements along a given axis evaluate to True.

In [49]:
np.all([[True,False],[True,True]])

False

# 15. any function

In [50]:
# it test whether any array element along a given axis evaluates to True.

In [51]:
np.any([[True,False],[True,True]])      #true bcs not equal to zero

True

# 16. floor function

In [56]:
# it return the floor of the input, element-wise.

In [52]:
n = np.array([-1.5,-1.2,-0.3,0.3,1.2,1.5,2.0])

In [53]:
np.floor(n)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

# 17. identity function

In [54]:
# it return the identity array.

In [55]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# 18. logspace function

In [57]:
# it return number space evenly on alog scale

In [58]:
np.logspace(2.0,3.0,num=3)

array([ 100.        ,  316.22776602, 1000.        ])

# 19. mgrid function

In [59]:
#it returns a dense multi-dimensional “meshgrid”.

In [60]:
np.mgrid[0:4,0:4]

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

# 20. ogrid function

In [61]:
#it returns an open multi-dimensional “meshgrid”.

In [62]:
np.ogrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [63]:
np.ogrid[0:4,0:4]


[array([[0],
        [1],
        [2],
        [3]]),
 array([[0, 1, 2, 3]])]

# 21. array_split function

In [64]:
# it split an array into multiple sub-arrays.

In [65]:
o = np.arange(9.0)

In [66]:
np.array_split(o, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

# 22. column_stack function

In [67]:
# it stack 1-D arrays as columns into a 2-D array.

In [68]:
a = np.array((1,5,7))
b = np.array((2,4,6))

In [69]:
np.column_stack((a,b))

array([[1, 2],
       [5, 4],
       [7, 6]])

# 23. dsplit function

In [70]:
#it split array into multiple sub-arrays along the 3rd axis (depth).

In [71]:
p = np.arange(16).reshape(2, 4, 2)

In [72]:
p

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [73]:
np.dsplit(p, 2)


[array([[[ 0],
         [ 2],
         [ 4],
         [ 6]],
 
        [[ 8],
         [10],
         [12],
         [14]]]),
 array([[[ 1],
         [ 3],
         [ 5],
         [ 7]],
 
        [[ 9],
         [11],
         [13],
         [15]]])]

# 24. dstack function

In [74]:
# it stack arrays in sequence depth wise (along third axis).

In [75]:
a = np.array((1,2,3))
b = np.array((4,5,6))

In [76]:
np.dstack((a,b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# 25. hsplit function

In [77]:
# it split an array into multiple sub-arrays horizontally (column-wise).

In [78]:
q = np.arange(20).reshape(5, 4)

In [79]:
q

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [80]:
np.hsplit(q, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

# 26. hstack function

In [81]:
# it stack arrays in sequence horizontally (column wise).

In [82]:
a = np.array((4,5,6))
b = np.array((7,8,9))

In [83]:
np.hstack((a,b))

array([4, 5, 6, 7, 8, 9])

# 27. ravel function

In [84]:
#it return a contiguous flattened array.

In [85]:
r = np.array([[1, 2, 3], [4, 5, 6]])

In [86]:
np.ravel(r)

array([1, 2, 3, 4, 5, 6])

# 28. repeat function

In [87]:
# it repeat elements of an array.

In [88]:
np.repeat(2, 4)

array([2, 2, 2, 2])

In [89]:
s = np.array([[1,2],[3,4]])

In [90]:
np.repeat(s, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

# 29. resize function

In [91]:
# it return a new array with the specified shape.

In [92]:
t=np.array([[1,2],[3,4]])

In [93]:
np.resize(t,(2,3))

array([[1, 2, 3],
       [4, 1, 2]])

# 30. vsplit function

In [94]:
# it split an array into multiple sub-arrays vertically (row-wise).

In [95]:
u = np.arange(20).reshape(4, 5)

In [96]:
u

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [97]:
np.vsplit(u, 2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

# 31. vstack function

In [98]:
# it stack arrays in sequence vertically (row wise).

In [99]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

In [100]:
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

# 32. where function

In [101]:
# it return elements chosen from x or y depending on condition.

In [102]:
a = np.arange(10)

In [103]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.where(a < 5)


(array([0, 1, 2, 3, 4], dtype=int64),)

# 33. sort function

In [105]:
# it return a sorted copy of an array.

In [106]:
v = np.array([[1,4],[3,1]])

In [107]:
np.sort(v)                # sort along the last axis

array([[1, 4],
       [1, 3]])

# 34. choose function

In [108]:
# it construct an array from an index array and a set of arrays to choose from.

In [109]:
w = [[1, 0, 1], [0, 1, 0], [1, 0, 1]]

In [110]:
choices = [-10, 10]

In [111]:
np.choose(w, choices)

array([[ 10, -10,  10],
       [-10,  10, -10],
       [ 10, -10,  10]])

# 35. compress function

In [112]:
# it return selected slices of an array along given axis.

In [113]:
x = np.array([[1, 2], [3, 4], [5, 6]])

In [114]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
np.compress([0, 1], x, axis=0)

array([[3, 4]])

# 36. cumprod function

In [116]:
# it return the cumulative product of elements along a given axis.

In [117]:
y = np.array([1,2,3])

In [118]:
np.cumprod(y)

array([1, 2, 6], dtype=int32)

# 37. inner function

In [119]:
# Inner product of two arrays.

In [120]:
a = np.array([1,2,3])
b = np.array([0,1,0])

In [121]:
np.inner(a, b)

2

# 38. ndarray.fill function

In [123]:
#Fill the array with a scalar value.

In [124]:
z = np.array([5, 6])

In [125]:
z.fill(2)

In [126]:
z

array([2, 2])

# 39. imag function

In [127]:
#it return the imaginary part of the complex argument.

In [128]:
a = np.array([1+2j, 3+4j, 5+6j])

In [129]:
a.imag

array([2., 4., 6.])

# 40. prod function

In [130]:
# it return the product of array elements over a given axis.

In [131]:
np.prod([1.,2.])

2.0

In [132]:
np.prod([[1.,2.],[3.,4.]])   # two dimensional

24.0

# 41. put function

In [133]:
# it replaces specified elements of an array with given values.

In [134]:
a = np.arange(6)

In [135]:
np.put(a, [0, 2], [-44, -55])

In [136]:
a

array([-44,   1, -55,   3,   4,   5])

# 42. putmask function

In [137]:
# it changes elements of an array based on conditional and input values.

In [138]:
x = np.arange(6).reshape(2, 3)

In [139]:
np.putmask(x, x>2, x**2)


In [140]:
x

array([[ 0,  1,  2],
       [ 9, 16, 25]])

# 43. real function

In [141]:
# it return the real part of the complex argument.

In [142]:
a = np.array([1+2j, 3+4j, 5+6j])

In [143]:
a.real

array([1., 3., 5.])

# 44. cov function

In [144]:
# Estimate a covariance matrix, given data and weights.

In [145]:
x = np.array([[0, 2], [1, 1], [2, 0]]).T

In [146]:
x

array([[0, 1, 2],
       [2, 1, 0]])

In [147]:
np.cov(x)

array([[ 1., -1.],
       [-1.,  1.]])

# 45. mean function

In [148]:
# it compute the arithmetic mean along the specified axis.

In [149]:
a = np.array([[1, 2], [3, 4]])

In [150]:
np.mean(a)

2.5

# 46. std function

In [151]:
# it compute the standard deviation along the specified axis.

In [152]:
a = np.array([[1, 2], [3, 4]])

In [153]:
np.std(a)

1.118033988749895

# 47. var function

In [154]:
# it compute the variance along the specified axis.

In [155]:
a = np.array([[1, 2], [3, 4]])

In [156]:
np.var(a)

1.25

# 48. cross function

In [157]:
# it return the cross product of two (arrays of) vectors.

In [158]:
x = [1, 2, 3]
y = [4, 5, 6]

In [159]:
np.cross(x, y)

array([-3,  6, -3])

# 49. dot function

In [164]:
# it return the dot product of two arrays. Specifically,

In [161]:
np.dot(3, 4)

12

In [162]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

In [163]:
np.dot(a, b)

array([[4, 1],
       [2, 2]])

# 50. vdot function

In [165]:
# it return the dot product of two vectors.

In [166]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])

In [167]:
np.vdot(a, b)

(70-8j)

In [168]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])

In [169]:
np.vdot(a, b)

30